### PR TITLE
update README, add building instructions for Linux

### PR DESCRIPTION
**Pull request by dvoromar**

### CODE REVIEW

**Comment by tokejepsen** [comment]
Running the emscripten compile results in this error; https://github.com/google/monster-mash/pull/3

I have updated the docker file PR to reflect this compile information.

The Linux compile instructions seem to work though.

**Comment by gumlooter** [comment]
Was not able to build using instructions here.
Build started, but 

```make[2]: Entering directory '/home/user/monster-mash/build/Release'
[  4%] Building CXX object CMakeFiles/monstermash.dir/defengarapl.cpp.o
/home/user/emsdk/upstream/emscripten/em++ -DAPP_VERSION=210301 -DEIGEN_MPL2_ONLY -DEIGEN_SPARSESOLVERBASE_H -DIGL_PARALLEL_FOR_FORCE_SERIAL -DIMAGE_MINIZ_EXTERNAL -DIMAGE_READ_WRITE -DIMAGE_SCALE -DNO_TIMER -DTRILIBRARY -DUSE_OPENGL_FOR_DRAWING_INSTEAD_OF_SDL -DUSE_SDL_GLES2 -D_SDL2_gfxPrimitives_h -I/home/user/monster-mash/src/../third_party -I/home/user/monster-mash/src/../third_party/eigen3-mod -I/home/user/monster-mash/src/../third_party/eigen3 -I/home/user/monster-mash/src/../third_party/libigl/include -I/home/user/monster-mash/src/../third_party/stb -I/home/user/monster-mash/src/../third_party/triangle -I/home/user/monster-mash/src/../third_party/zip-mod -I/home/user/monster-mash/src/../third_party/SDL2_gfx -I/home/user/monster-mash/src/../third_party/SDL2_gfx-mod -sWASM=1 -sUSE_SDL=2 -sUSE_SDL_TTF=2 -sALLOW_MEMORY_GROWTH=1 -sMINIFY_HTML=0 -sENVIRONMENT=web -Wno-sign-compare -Werror=return-type -Wno-narrowing -sFULL_ES2=1 -std=gnu++17 -o CMakeFiles/monstermash.dir/defengarapl.cpp.o -c /home/user/monster-mash/src/defengarapl.cpp
In file included from /home/user/monster-mash/src/defengarapl.cpp:19:
In file included from /home/user/monster-mash/src/../third_party/libigl/include/igl/fit_rotations.h:57:
In file included from /home/user/monster-mash/src/../third_party/libigl/include/igl/fit_rotations.cpp:12:
In file included from /home/user/monster-mash/src/../third_party/libigl/include/igl/polar_dec.h:50:
/home/user/monster-mash/src/../third_party/libigl/include/igl/polar_dec.cpp:42:17: error: use of undeclared identifier 'FE_UNDERFLOW'
  feclearexcept(FE_UNDERFLOW);
                ^
/home/user/monster-mash/src/../third_party/libigl/include/igl/polar_dec.cpp:44:19: error: use of undeclared identifier 'FE_UNDERFLOW'
  if(fetestexcept(FE_UNDERFLOW) || eig.eigenvalues()(0)/eig.eigenvalues()(2)<th)
                  ^
2 errors generated.
em++: error: '/home/user/emsdk/upstream/bin/clang++ -DEMSCRIPTEN -fignore-exceptions -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr -I/home/user/emsdk/upstream/emscripten/cache/sysroot/include/freetype2/freetype -Xclang -isystem/home/user/emsdk/upstream/emscripten/cache/sysroot/include/SDL2 -I/home/user/emsdk/upstream/emscripten/cache/ports-builds/harfbuzz/include/harfbuzz -DTTF_USE_HARFBUZZ=1 -target wasm32-unknown-emscripten -D__EMSCRIPTEN_major__=2 -D__EMSCRIPTEN_minor__=0 -D__EMSCRIPTEN_tiny__=14 -D_LIBCPP_ABI_VERSION=2 -Dunix -D__unix -D__unix__ -flegacy-pass-manager -Werror=implicit-function-declaration --sysroot=/home/user/emsdk/upstream/emscripten/cache/sysroot -Xclang -iwithsysroot/include/compat -DAPP_VERSION=210301 -DEIGEN_MPL2_ONLY -DEIGEN_SPARSESOLVERBASE_H -DIGL_PARALLEL_FOR_FORCE_SERIAL -DIMAGE_MINIZ_EXTERNAL -DIMAGE_READ_WRITE -DIMAGE_SCALE -DNO_TIMER -DTRILIBRARY -DUSE_OPENGL_FOR_DRAWING_INSTEAD_OF_SDL -DUSE_SDL_GLES2 -D_SDL2_gfxPrimitives_h -I/home/user/monster-mash/src/../third_party -I/home/user/monster-mash/src/../third_party/eigen3-mod -I/home/user/monster-mash/src/../third_party/eigen3 -I/home/user/monster-mash/src/../third_party/libigl/include -I/home/user/monster-mash/src/../third_party/stb -I/home/user/monster-mash/src/../third_party/triangle -I/home/user/monster-mash/src/../third_party/zip-mod -I/home/user/monster-mash/src/../third_party/SDL2_gfx -I/home/user/monster-mash/src/../third_party/SDL2_gfx-mod -Wno-sign-compare -Werror=return-type -Wno-narrowing -std=gnu++17 -c /home/user/monster-mash/src/defengarapl.cpp -o CMakeFiles/monstermash.dir/defengarapl.cpp.o' failed (1)
make[2]: *** [CMakeFiles/monstermash.dir/build.make:98: CMakeFiles/monstermash.dir/defengarapl.cpp.o] Error 1
make[2]: Leaving directory '/home/user/monster-mash/build/Release'
make[1]: *** [CMakeFiles/Makefile2:98: CMakeFiles/monstermash.dir/all] Error 2
make[1]: Leaving directory '/home/user/monster-mash/build/Release'
make: *** [Makefile:106: all] Error 2```

**Comment by tokejepsen** [comment]
@gumlooter have a look at #3 for further information about this.

**Comment by gumlooter** [comment]
@tokejepsen sorry for missing your previous note, commit is definitely fix the error.

**Comment by dvoromar** [comment]
@googlebot I signed it!

**Comment by dvoromar** [comment]
Great you were able to resolve the compiler error! I remember dealing with it similarly in the past. This PR now also fixes this issue.

**Pull request merged**
