### PR TITLE
Initial docker commit.

### PR DESCRIPTION
**Pull request by tokejepsen**
This is a response to #1, and should serve as a detailed discussion on making a docker file for compiling the project.

### CODE REVIEW

**Comment by tokejepsen** [comment]
There is currently an issue with `sdl2_ttf` port in emscripten so for now have patched with latest commit; https://github.com/emscripten-core/emscripten/commit/0aec639126c5274236c40351f77063b8addc85cc. Hopefully there will be an update to the docker image, which we can switch to later.

**Comment by tokejepsen** [comment]
@googlebot I signed it!

**Comment by tokejepsen** [comment]
This docker build is currently failing with this message:

```
[  8%] Building CXX object CMakeFiles/monstermash.dir/defengarapl.cpp.o
/emsdk/upstream/emscripten/em++  -DAPP_VERSION=210213 -DEIGEN_MPL2_ONLY -DEIGEN_SPARSESOLVERBASE_H -DIGL_PARALLEL_FOR_FORCE_SERIAL -DIMAGE_MINIZ_EXTERNAL -DIMAGE_READ_WRITE -DIMAGE_SCALE -DNO_TIMER -DTRILIBRARY -DUSE_OPENGL_FOR_DRAWING_INSTEAD_OF_SDL -DUSE_SDL_GLES2 -D_SDL2_gfxPrimitives_h @CMakeFiles/monstermash.dir/includes_CXX.rsp -sWASM=1 -sUSE_SDL=2 -sUSE_SDL_TTF=2 -sALLOW_MEMORY_GROWTH=1 -sMINIFY_HTML=0 -sENVIRONMENT=web -Wno-sign-compare -Werror=return-type -Wno-narrowing -sFULL_ES2=1 -std=gnu++17 -o CMakeFiles/monstermash.dir/defengarapl.cpp.o -c /usr/src/monster-mash/src/defengarapl.cpp
In file included from /usr/src/monster-mash/src/defengarapl.cpp:19:
In file included from /usr/src/monster-mash/src/../third_party/libigl/include/igl/fit_rotations.h:57:
In file included from /usr/src/monster-mash/src/../third_party/libigl/include/igl/fit_rotations.cpp:12:
In file included from /usr/src/monster-mash/src/../third_party/libigl/include/igl/polar_dec.h:50:
/usr/src/monster-mash/src/../third_party/libigl/include/igl/polar_dec.cpp:42:17: error: use of undeclared identifier 'FE_UNDERFLOW'
  feclearexcept(FE_UNDERFLOW);
                ^
/usr/src/monster-mash/src/../third_party/libigl/include/igl/polar_dec.cpp:44:19: error: use of undeclared identifier 'FE_UNDERFLOW'
  if(fetestexcept(FE_UNDERFLOW) || eig.eigenvalues()(0)/eig.eigenvalues()(2)<th)
                  ^
2 errors generated.
em++: error: '/emsdk/upstream/bin/clang++ -DEMSCRIPTEN -fignore-exceptions -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr -Xclang -isystem/emsdk/upstream/emscripten/cache/sysroot/include/SDL2 -I/emsdk/upstream/emscripten/cache/sysroot/include/freetype2/freetype -I/emsdk/upstream/emscripten/cache/ports-builds/harfbuzz/include/harfbuzz -DTTF_USE_HARFBUZZ=1 -target wasm32-unknown-emscripten -D__EMSCRIPTEN_major__=2 -D__EMSCRIPTEN_minor__=0 -D__EMSCRIPTEN_tiny__=13 -D_LIBCPP_ABI_VERSION=2 -Dunix -D__unix -D__unix__ -Werror=implicit-function-declaration --sysroot=/emsdk/upstream/emscripten/cache/sysroot -Xclang -iwithsysroot/include/compat -DAPP_VERSION=210213 -DEIGEN_MPL2_ONLY -DEIGEN_SPARSESOLVERBASE_H -DIGL_PARALLEL_FOR_FORCE_SERIAL -DIMAGE_MINIZ_EXTERNAL -DIMAGE_READ_WRITE -DIMAGE_SCALE -DNO_TIMER -DTRILIBRARY -DUSE_OPENGL_FOR_DRAWING_INSTEAD_OF_SDL -DUSE_SDL_GLES2 -D_SDL2_gfxPrimitives_h -I/usr/src/monster-mash/src/../third_party -I/usr/src/monster-mash/src/../third_party/eigen3-mod -I/usr/src/monster-mash/src/../third_party/eigen3 -I/usr/src/monster-mash/src/../third_party/libigl/include -I/usr/src/monster-mash/src/../third_party/stb -I/usr/src/monster-mash/src/../third_party/triangle -I/usr/src/monster-mash/src/../third_party/zip-mod -I/usr/src/monster-mash/src/../third_party/SDL2_gfx -I/usr/src/monster-mash/src/../third_party/SDL2_gfx-mod -Wno-sign-compare -Werror=return-type -Wno-narrowing -std=gnu++17 -c /usr/src/monster-mash/src/defengarapl.cpp -o CMakeFiles/monstermash.dir/defengarapl.cpp.o' failed (1)
make[2]: *** [CMakeFiles/monstermash.dir/build.make:81: CMakeFiles/monstermash.dir/defengarapl.cpp.o] Error 1
make[2]: Leaving directory '/usr/src/monster-mash'
make[1]: Leaving directory '/usr/src/monster-mash'
make[1]: *** [CMakeFiles/Makefile2:76: CMakeFiles/monstermash.dir/all] Error 2
make: *** [Makefile:87: all] Error 2
The command '/bin/sh -c make' returned a non-zero code: 2
```

I dont have any c++ experience so troubleshooting this might take a while. Any help is very much appreciated!

**Comment by tokejepsen** [comment]
The failing emscripten build could potentially also be due to issues with the common structs, which precedes the error above;

```
In file included from /usr/src/monster-mash/src/main.cpp:17:
In file included from /usr/src/monster-mash/src/mainwindow.h:18:
In file included from /usr/src/monster-mash/src/commonStructs.h:26:
/usr/src/monster-mash/src/cpanim.h:26:17: warning: anonymous non-C-compatible type given name for linkage purposes by typedef declaration; add a tag name here [-Wnon-c-typedef-for-linkage]
  typedef struct {
                ^
                 Keypose
/usr/src/monster-mash/src/cpanim.h:29:5: note: type is not C-compatible due to this default member initializer
    bool empty = true;
    ^~~~~~~~~~
/usr/src/monster-mash/src/cpanim.h:32:5: note: type is given name 'Keypose' for linkage purposes by this typedef declaration
  } Keypose;
    ^
In file included from /usr/src/monster-mash/src/main.cpp:17:
In file included from /usr/src/monster-mash/src/mainwindow.h:18:
/usr/src/monster-mash/src/commonStructs.h:145:15: warning: anonymous non-C-compatible type given name for linkage purposes by typedef declaration; add a tag name here [-Wnon-c-typedef-for-linkage]
typedef struct {
              ^
               PauseStatus
/usr/src/monster-mash/src/commonStructs.h:146:20: note: type is not C-compatible due to this default member initializer
  bool defPaused = false;
                   ^~~~~
/usr/src/monster-mash/src/commonStructs.h:148:3: note: type is given name 'PauseStatus' for linkage purposes by this typedef declaration
} PauseStatus;
  ^
2 warnings generated.
```

**Comment by tokejepsen** [comment]
Resolved the warnings above and it does not seem to fix the errors.

**Comment by tokejepsen** [comment]
The undeclared identifier comes from; https://en.cppreference.com/w/cpp/numeric/fenv/feclearexcept

It seems like the support for this has been removed in emscripten; https://emscripten.org/docs/introducing_emscripten/release_notes.html on the release `1.39.15: 05/06/2020`:
```
- Stop defining `FE_INEXACT` and other floating point exception macros in libc,
  since we don't support them. That also prevents musl from including code using
  pragmas that don't make sense for wasm. Ifdef out other uses of those pragmas
  as well, as tip of tree LLVM now fails to compile them on wasm. (#11087)
```
https://github.com/emscripten-core/emscripten/issues/11086

**Comment by rahulpowar** [comment]
Should have looked at this before I started my own Dockerfile. At any rate, https://github.com/rahulpowar/monster-mash is working with a hack for `FE_UNDERFLOW` as I could not get em++ version 1.39.14 to work.

**Comment by tokejepsen** [comment]
Amazing stuff @rahulpowar!

**Comment by tokejepsen** [comment]
@rahulpowar just tested your Dockerfile and it working here!

Dont wanna steal any credit, so instead of my committing to this PR maybe it better for you to either make your own PR or PR to my branch,

**Comment by tokejepsen** [comment]
@dvoromar there seems to be a couple of icons missing from this repository coming from a directory called `/imgs`. Would it be possible to add those to the repository?

**Comment by rahulpowar** [comment]
> @rahulpowar just tested your Dockerfile and it working here!
> 
> Dont wanna steal any credit, so instead of me committing to this PR maybe it better for you to either make your own PR or PR to my branch,

I don't mind if you want to push this up. I am unsure about the impact of hacking out FE_UNDERFLOW so someone should look at that too.

**Comment by dvoromar** [comment]
> @dvoromar there seems to be a couple of icons missing from this repository coming from a directory called `/imgs`. Would it be possible to add those to the repository?

I'll see what I can do with it.

**Comment by tokejepsen** [comment]
> Should have looked at this before I started my own Dockerfile. At any rate, https://github.com/rahulpowar/monster-mash is working with a hack for `FE_UNDERFLOW` as I could not get em++ version 1.39.14 to work.

Reverted the changes to the third party code in favour of @dvoromar cmake hack, to keep third party code intact.

**Comment by tokejepsen** [comment]
> @dvoromar there seems to be a couple of icons missing from this repository coming from a directory called `/imgs`. Would it be possible to add those to the repository?

Any update on getting these icons?
Think this is only thing stopping this PR to be complete.

**Comment by dvoromar** [comment]
Hi @tokejepsen, sorry for the late answer! As a workaround, before we put the icons here, you can simply make the script download the necessary images from the website.

**Comment by tokejepsen** [comment]
> Hi @tokejepsen, sorry for the late answer! As a workaround, before we put the icons here, you can simply make the script download the necessary images from the website.

Where are the icons located on the website?

**Comment by tokejepsen** [comment]
All `imgs` files are downloaded on docker build from the website now.

This PR is ready to merge now.

**Pull request closed without merging**
